import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'

// const inter = Inter({ subsets: ['latin'] })
const geistSans = GeistSans

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={`${geistSans.variable}`} lang="en">
      <body className={`antialiased bg-mirage-50 text-mirage-950`}>{children}</body>
    </html>
  )
}
